include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - "example/**"
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:

dart_code_metrics:
  anti-patterns:
    - long-method:
        severity: warning
    - long-parameter-list:
        severity: warning
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - "test/**"
  rules:
    - newline-before-return
    - prefer-trailing-comma
    - no-equal-then-else
