name: github_viewer
description: Github Viewer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # 状態管理
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.0-dev.9

  # ロギング周り
  logger: ^1.1.0
  stack_trace: ^1.10.0

  # 通信回り
  http: ^0.13.5

  # メタプログラミング
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0

  # ルーティング
  go_router: ^4.2.7

  # UI周りのロジック
  rxdart: ^0.27.5

dev_dependencies:
  # テスト
  flutter_test:
    sdk: flutter
  fake_async: ^1.3.0
  mockito: ^5.3.0

  # Lints
  flutter_lints: ^2.0.0
  flutter_hooks_lint_plugin: ^0.5.2

  # メタプログラミング
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  dart_code_metrics: ^4.17.0

  # タスクランナー
  grinder: ^0.9.2

flutter:
  uses-material-design: true
